name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    uses: LoganBarnett/rust-template/.github/workflows/reusable-publish.yml@main
    with:
      crate-name: rust-template-lib
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
